### ISSUE TITLE
Builds on 10.1 AMD64 as KVM/QEMU guest

### ISSUE THREAD

**Issue by deadmanrod** [ethoms/freebsd-ports#1]
Build went without a hitch.  I'll finish configuration and testing tomorrow.  Wanted to point out that your rc.d script does not check with /etc/rc.conf for permission.  You'll need to require something like
sogod_enable="YES"
in /etc/rc.conf for the port to be accepted.  Thought you should know.

**Comment by ethoms** [comment]
Thanks for pointing that out. I will correct it soon, when I next work on the port. I got it to build on 9.2 but I need to test it on 8.4 yet. I haven't had time to work on getting this into the ports tree. I really should make the effort or the effort so far will be wasted.

**Comment by ethoms** [comment]
OK, the port has been updated to fix the rcvar sogod_enable default to NO.

**Comment by ethoms** [comment]
@deadmanrod 
Can you please test building the port again on an updated ports tree? I have tried it just now on a fresh 8.4, 9.3 and 10.1 and it will no longer build. It fails on the devel/sope port with no information as to why it failed:

root@test101amd64:/usr/ports/devel/sope # make
===>  Building for sope-2.2.14_1
make[2]: cannot open Makefile.

make[2]: stopped in /usr/ports/devel/sope/work/SOPE
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
**\* Error code 1

Stop.
make[1]: stopped in /usr/ports/devel/sope
**\* Error code 1

Stop.
make: stopped in /usr/ports/devel/sope

**Comment by ethoms** [comment]
OK, Ive tracked down the problem, me thinks. The ports tree file /usr/ports/Mk/bsd.gnustep.mk is now missing in the latest tree. So perhaps the use of Makefile drirectives like USE_GNUSTEP_MAKE=yes has changed, or perhaps there was an accident by the ports tree team.

**Comment by ethoms** [comment]
OK, I found it here: 
https://freshports.org/sanity_test_failures.php?message_id=201504090744.t397igI6043596@svn.freebsd.org

The "USE_GNUSTEP_*" have been replaced with "USES=gnustep objc" and "USE_GNUSTEP=base build".

I'm updating and testing the ports devel/sope and www/sogo just now, to fit into the new guidelines. Strange how I can't find this change in the ports-announce or ports mailing list.

**Comment by ethoms** [comment]
The ports devel/sope and www/sogo have been updated to fix the changes to GNUstep make directives. It's now building again on 9.3, I'm testing a build on 10.1, and then I'll test 8.4.
